import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { atomicWriteFile } from './fs-atomic.js';
import {
  MalformedManagedBlockError,
  splitManagedBlock,
  upsertManagedBlock,
} from './managed-block.js';
import { KK_NAVIGATION_DIRECTIVE } from './session-start.js';

/**
 * Sentinel markers around the kenkeep-managed pointer block in the repo's
 * AGENTS.md. The block is the knowledge base's "lobby" for every surface
 * that reads agents files natively (Codex, OpenCode, Cursor, humans on the
 * web UI): a one-paragraph pointer at the entry catalog plus the shared
 * descent directive. Deterministic — no LLM writes here; the catalog itself
 * lives in ENTRY.md and is regenerated by `index rebuild`.
 */
export const AGENTS_BLOCK_START = '<!-- >>> kenkeep:kk-index >>> -->';
export const AGENTS_BLOCK_END = '<!-- <<< kenkeep:kk-index <<< -->';

// The static kk-index pointer block. It enters the knowledge base at the entry
// catalog and then reuses the exact descent wording shipped by the
// SessionStart hook, so the always-on file surface and the hook surface share
// one source of truth and cannot drift. The descent body itself is never
// re-typed here; it comes from KK_NAVIGATION_DIRECTIVE.
export const AGENTS_POINTER = [
  'You are required to load [.ai/kenkeep/ENTRY.md](.ai/kenkeep/ENTRY.md), the small curated entry catalog for this repo. Enter there and descend using progressive disclosure principles.',
  '',
  KK_NAVIGATION_DIRECTIVE,
].join('\n');

const AGENTS_MARKERS = { start: AGENTS_BLOCK_START, end: AGENTS_BLOCK_END };

/**
 * Idempotently writes the kenkeep pointer block into `file` (the repo's
 * AGENTS.md): creates the file when absent, replaces an existing block in
 * place, appends when no block exists, and preserves all user content
 * outside the markers. Returns true when the file's bytes changed. Called
 * by `init`, `init --upgrade`, and `index rebuild` so the block tracks the
 * current directive wording without any manual step.
 *
 * Follows the shared malformed-sentinel policy (`managed-block.ts`): an
 * orphaned, duplicated or reversed marker throws a
 * `MalformedManagedBlockError` naming the file and leaves it untouched.
 */
export function ensureAgentsKkBlock(file: string): boolean {
  const existing = existsSync(file) ? readFileSync(file, 'utf8') : '';
  const next = upsertManagedBlock(existing, AGENTS_MARKERS, AGENTS_POINTER, file);
  if (next === existing) return false;
  atomicWriteFile(file, next);
  return true;
}

/**
 * Throws the `MalformedManagedBlockError` that `ensureAgentsKkBlock(file)`
 * would throw, without writing anything. An absent file or an absent block is
 * fine (both are writable). `index rebuild` checks this before its first owned
 * write, and a caller whose own writes land before its nested rebuild (pack
 * import) checks it before those writes, so the refusal never arrives after
 * the files it should have prevented.
 */
export function assertAgentsKkBlockWritable(file: string): void {
  if (!existsSync(file)) return;
  splitManagedBlock(readFileSync(file, 'utf8'), AGENTS_MARKERS, file);
}

export interface AgentsBlockIssue {
  file: string;
  message: string;
  action: string;
}

/**
 * Deterministic drift check for the AGENTS.md pointer block, consumed by
 * `lint` as warn-level findings (never errors — a missing lobby degrades
 * discoverability, it does not corrupt the knowledge base):
 *   - AGENTS.md absent, missing the sentinel block, or carrying a malformed one
 *     (orphaned, duplicated or reversed markers per `managed-block.ts`);
 *   - the block's pointer target (.ai/kenkeep/ENTRY.md) absent while the
 *     tree has leaves (an empty, just-initialized KB legitimately has no
 *     catalog yet).
 */
export function checkAgentsKkBlock(
  root: string,
  kkDir: string,
  nodeCount: number
): AgentsBlockIssue[] {
  const issues: AgentsBlockIssue[] = [];
  const agentsFile = join(root, 'AGENTS.md');
  if (!existsSync(agentsFile)) {
    issues.push({
      file: 'AGENTS.md',
      message:
        'AGENTS.md does not exist, so agents-file surfaces never discover the knowledge base',
      action:
        'run `npx kenkeep init --harnesses <id[,id,...]> --upgrade` to seed the pointer block',
    });
    return issues;
  }
  const body = readFileSync(agentsFile, 'utf8');
  try {
    if (!splitManagedBlock(body, AGENTS_MARKERS, agentsFile).found) {
      issues.push({
        file: 'AGENTS.md',
        message: 'AGENTS.md is missing the kenkeep pointer block',
        action: 'run `npx kenkeep index rebuild` (or `init --upgrade`) to restore it',
      });
    }
  } catch (err) {
    if (!(err instanceof MalformedManagedBlockError)) throw err;
    issues.push({
      file: 'AGENTS.md',
      message: 'AGENTS.md has a malformed kenkeep pointer block (orphaned or duplicated markers)',
      action: `keep exactly one "${AGENTS_BLOCK_START}" line before one "${AGENTS_BLOCK_END}" line (or delete both), then run \`npx kenkeep index rebuild\``,
    });
  }
  if (nodeCount > 0 && !existsSync(join(kkDir, 'ENTRY.md'))) {
    issues.push({
      file: '.ai/kenkeep/ENTRY.md',
      message:
        'the pointer block targets .ai/kenkeep/ENTRY.md, which does not exist despite a populated tree',
      action: 'run `npx kenkeep index rebuild` to regenerate the entry catalog',
    });
  }
  return issues;
}
