import { execFile, execFileSync } from 'node:child_process';
import {
  existsSync,
  lstatSync,
  mkdtempSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, isAbsolute, join, posix, relative, resolve, sep } from 'node:path';
import { promisify } from 'node:util';
import yaml from 'js-yaml';
import { preflightIndexRebuild, rebuildOutputFiles, runIndexRebuild } from './index-rebuild.js';
import { LEGACY_NODE_SCHEMA_VERSION, migrateNodesTreeToV3 } from './migrate-okf-v3.js';
import { agentsKkBlockNeedsWrite } from '../lib/agents-block.js';
import { readFolderSummaries, writeFolderSummaries } from '../lib/folder-summaries.js';
import { atomicWriteFile, copyTree } from '../lib/fs-atomic.js';
import { log } from '../lib/log.js';
import {
  findPackSymlinks,
  PACK_KNOWLEDGE_DIRNAME,
  PACK_MANIFEST_FILENAME,
  validatePack,
} from '../lib/pack.js';
import {
  InvalidNodeFrontmatterError,
  OldLayoutError,
  readAllNodes,
  type NodeFile,
} from '../lib/nodes.js';
import { assertContained, PACK_NAME_PATTERN } from '../lib/path-safety.js';
import { planRenderedLinkRefresh, refreshRenderedLinks } from '../lib/rendered-links.js';
import { findKenkeepRoot, repoPaths } from '../lib/paths.js';
import {
  mergeRedirectsLedgers,
  readRedirectsLedger,
  REDIRECTS_FILENAME,
  writeRedirectsLedger,
  type RedirectsLedger,
} from '../lib/redirects.js';
import { NODE_SCHEMA_VERSION } from '../lib/schemas.js';

const exec = promisify(execFile);

export interface AcquiredPack {
  packRoot: string;
  resolvedSource: string;
}

export type PackSourceAcquirer = (source: string, tmpRoot: string) => Promise<AcquiredPack>;

export interface PackImportOptions {
  as?: string | undefined;
  migrate?: boolean | undefined;
  acquireSource?: PackSourceAcquirer | undefined;
}

/**
 * Everything the graft will write, minted and containment-checked before the
 * first byte lands. Only validated leaves are copied: reserved `index.md`
 * files are regenerated by the rebuild, never imported, and the pack's ledger
 * is merged into the consumer root, the one place the ledger reader looks.
 */
interface GraftPlan {
  destinationDir: string;
  leaves: Array<{ src: string; dest: string }>;
  /** The validated pack leaves as they will sit under `nodes/` once grafted. */
  grafted: NodeFile[];
  /** Ids of the grafted leaves: the scope of the rendered-link refresh. */
  ids: Set<string>;
  folderSummaries: Map<string, string>;
  /** The merged ledger to write, or null when the pack retires nothing. */
  ledger: RedirectsLedger | null;
  redirectsMerged: number;
}

interface GitHubRepo {
  owner: string;
  repo: string;
}

export async function runPackImportCommand(
  source: string,
  opts: PackImportOptions = {}
): Promise<number> {
  const root = findKenkeepRoot();
  if (!root || !existsSync(repoPaths(root).installedVersionFile)) {
    log.error(
      'pack import: kenkeep is not initialized in this repo. Run `npx kenkeep init --harnesses <id[,id,...]>`.'
    );
    return 1;
  }
  const paths = repoPaths(root);
  let undo: string[];
  try {
    undo = requireRestorableTree(root, paths.kkDir);
  } catch (err) {
    log.error(`pack import: ${(err as Error).message}`);
    return 1;
  }

  const tmpRoot = mkdtempSync(join(tmpdir(), 'kk-pack-import-'));
  try {
    const acquire = opts.acquireSource ?? acquirePackSource;
    const acquired = await acquire(source, tmpRoot);

    // Links are refused before the pack is read, copied or migrated: a linked
    // manifest, leaf or index would otherwise read local files into the KB.
    const symlinks = findPackSymlinks(acquired.packRoot);
    if (symlinks.length > 0) {
      log.error(`pack import: ${acquired.resolvedSource} is not a valid kenkeep pack:`);
      log.error(
        `  symlink(s) in pack content are not allowed (links are never followed): ${symlinks.join(', ')}`
      );
      return 1;
    }

    // A schema bump is a clean break: readers reject a mismatch rather than
    // shimming it. Conversion is available but stays opt-in, so a consumer
    // never silently imports third-party content a migration rewrote.
    const isLegacy = packManifestSchemaVersion(acquired.packRoot) === LEGACY_NODE_SCHEMA_VERSION;
    if (isLegacy && opts.migrate !== true) {
      log.error(
        `pack import: ${acquired.resolvedSource} declares node schema ${LEGACY_NODE_SCHEMA_VERSION}, ` +
          `but this kenkeep installs schema ${NODE_SCHEMA_VERSION}. Re-run with --migrate to convert ` +
          `a copy of the pack before importing; the source is not modified.`
      );
      return 1;
    }
    const packRoot = isLegacy ? migrateLegacyPack(acquired.packRoot, tmpRoot) : acquired.packRoot;

    // The pack is validated against the tree it will join: identity
    // collisions and edge resolution are decided over pack + consumer.
    let consumerNodes: NodeFile[];
    try {
      consumerNodes = readAllNodes(paths.nodesDir);
    } catch (err) {
      if (err instanceof InvalidNodeFrontmatterError || err instanceof OldLayoutError) {
        log.error(`pack import: ${err.message}`);
        return 1;
      }
      throw err;
    }
    const consumerLedger = readRedirectsLedger(paths.nodesDir);
    const validation = validatePack(packRoot, {
      consumerIds: new Map(consumerNodes.map(node => [node.frontmatter.kk_id, node.relPath])),
      consumerLedger,
    });
    if (!validation.ok || !validation.manifest || !validation.nodes || !validation.ledger) {
      log.error(`pack import: ${acquired.resolvedSource} is not a valid kenkeep pack:`);
      for (const error of validation.errors) log.error(`  ${error}`);
      for (const warning of validation.warnings) log.warn(`  ${warning}`);
      return 1;
    }
    for (const warning of validation.warnings) log.warn(`pack import: ${warning}`);

    const destinationName = opts.as ?? validation.manifest.name;
    if (!PACK_NAME_PATTERN.test(destinationName)) {
      log.error(
        `pack import: destination branch "${destinationName}" must match ${PACK_NAME_PATTERN.source}`
      );
      return 1;
    }

    const destinationDir = assertContained(paths.nodesDir, join(paths.nodesDir, destinationName));
    if (existsSync(destinationDir)) {
      log.error(
        `pack import: destination nodes/${destinationName}/ already exists; use --as <name> to import under a different branch.`
      );
      return 1;
    }

    const plan = planGraft({
      nodes: validation.nodes,
      nodesDir: paths.nodesDir,
      knowledgeDir: join(packRoot, PACK_KNOWLEDGE_DIRNAME),
      destinationDir,
      destinationName,
      manifestSummary: validation.manifest.summary,
      consumerLedger,
      packLedger: validation.ledger,
    });

    // The rebuild that follows the graft refuses a malformed project config
    // or AGENTS.md pointer block, and does so on its last step. Both are
    // known now, so they are checked before the first byte lands, as is every
    // existing file the graft and the rebuild would replace.
    try {
      preflightIndexRebuild(root);
    } catch (err) {
      log.error(
        `pack import: the index rebuild after the graft would fail, so nothing was imported.\n` +
          `  ${(err as Error).message}`
      );
      return 1;
    }
    try {
      refuseUnsafeOutputs(root, plan, consumerNodes, consumerLedger);
    } catch (err) {
      log.error(`pack import: nothing was imported, ${(err as Error).message}`);
      return 1;
    }

    try {
      applyGraft(plan, paths.nodesDir);
      const rebuildCode = await runIndexRebuild();
      if (rebuildCode !== 0) throw new Error(`index rebuild failed with exit code ${rebuildCode}`);
    } catch (err) {
      log.error(
        [
          `pack import: graft into nodes/${destinationName}/ failed: ${(err as Error).message}`,
          'Undo every change this import made with:',
          ...undo.map(command => `  ${command}`),
        ].join('\n')
      );
      return 1;
    }

    log.plain(`Source: ${acquired.resolvedSource}`);
    log.plain(`Destination: nodes/${destinationName}/`);
    log.plain(`Nodes grafted: ${plan.leaves.length}`);
    log.plain(`Redirects merged: ${plan.redirectsMerged}`);
    log.success('Indexes rebuilt.');
    return 0;
  } catch (err) {
    log.error(`pack import: ${(err as Error).message}`);
    return 1;
  } finally {
    rmSync(tmpRoot, { recursive: true, force: true });
  }
}

/**
 * Read the manifest's declared node schema version without validating anything
 * else, so a legacy pack can be routed to migration before `validatePack` fails
 * it on the schema equality gate. Anything unreadable returns null and falls
 * through to normal validation, which reports the real problem.
 */
function packManifestSchemaVersion(packRoot: string): number | null {
  const file = join(packRoot, PACK_MANIFEST_FILENAME);
  if (!existsSync(file)) return null;
  try {
    const data = yaml.load(readFileSync(file, 'utf8'));
    if (data === null || typeof data !== 'object' || Array.isArray(data)) return null;
    const value = (data as Record<string, unknown>)['schema_version'];
    return typeof value === 'number' ? value : null;
  } catch {
    return null;
  }
}

/**
 * Convert a pack published against the previous node schema, returning the root
 * to import from. Only reached once the caller has confirmed the pack is legacy
 * and that `--migrate` was passed.
 *
 * Without this a v2 pack is simply unusable: `validatePack` requires the
 * manifest's schema_version to equal the installed node schema exactly, so an
 * author who published under v2 has no path forward and a consumer has no way
 * in. Gating it behind a flag keeps the schema break clean: nothing is rewritten
 * unless the consumer asked for it.
 *
 * The conversion runs on a copy staged under the import's own temp root, never
 * on the acquired tree. That matters because a directory source points at a
 * real directory the user owns, and importing must never rewrite it.
 *
 * A migrated v2 pack also recovers its folder summaries for free: v2 kept them
 * in `index.md` frontmatter, and the migration harvests those into the sidecar
 * registry that v3 import already knows how to merge.
 */
function migrateLegacyPack(packRoot: string, tmpRoot: string): string {
  const staged = join(tmpRoot, 'migrated');
  copyTree(packRoot, staged);

  const summary = migrateNodesTreeToV3(join(staged, PACK_KNOWLEDGE_DIRNAME));

  const manifestFile = join(staged, PACK_MANIFEST_FILENAME);
  const manifest = yaml.load(readFileSync(manifestFile, 'utf8')) as Record<string, unknown>;
  manifest['schema_version'] = NODE_SCHEMA_VERSION;
  atomicWriteFile(
    manifestFile,
    yaml.dump(manifest, { indent: 2, lineWidth: 0, noRefs: true, sortKeys: true })
  );

  log.warn(
    `pack import: --migrate converted a copy of this pack from node schema ` +
      `${LEGACY_NODE_SCHEMA_VERSION} to ${NODE_SCHEMA_VERSION} (${summary.converted} node(s), ` +
      `${summary.folder_summaries} folder summary/summaries recovered). The source was not modified.`
  );
  for (const collision of summary.collisions) {
    log.warn(
      `pack import: ${collision.path}: authored heading(s) ${collision.headings.join(', ')} ` +
        `collide with kenkeep-generated sections; review the imported node.`
    );
  }
  return staged;
}

export async function acquirePackSource(source: string, tmpRoot: string): Promise<AcquiredPack> {
  // A directory is the shape `pack export` produces, so accepting it lets an
  // author import what they just exported without tarring it first. Import only
  // ever reads from packRoot, so pointing at the real directory is safe.
  const localDir = isAbsolute(source) ? source : resolve(process.cwd(), source);
  if (existsSync(localDir) && statSync(localDir).isDirectory()) {
    return {
      packRoot: locatePackRoot(localDir),
      resolvedSource: localDir,
    };
  }

  if (source.endsWith('.tar.gz')) {
    const tarball = isAbsolute(source) ? source : resolve(process.cwd(), source);
    if (!existsSync(tarball)) throw new Error(`tarball does not exist (${tarball})`);
    const extractDir = join(tmpRoot, 'local');
    await extractTarball(tarball, extractDir);
    return {
      packRoot: locatePackRoot(extractDir),
      resolvedSource: tarball,
    };
  }

  const repo = parseGitHubSource(source);
  if (!repo) {
    throw new Error(
      `unsupported pack source "${source}"; use owner/repo, a github.com URL, a .tar.gz path, or a pack directory.`
    );
  }

  const tarballUrl = await resolveGitHubTarballUrl(repo);
  const tarball = await downloadTarball(tarballUrl, join(tmpRoot, `${repo.repo}.tar.gz`));
  const extractDir = join(tmpRoot, 'github');
  await extractTarball(tarball, extractDir);
  return {
    packRoot: locatePackRoot(extractDir),
    resolvedSource: `${repo.owner}/${repo.repo} (${tarballUrl})`,
  };
}

/**
 * Mint every output path and compute every merged artifact without touching
 * the consumer. Each leaf destination is containment-checked against `nodes/`.
 * Only validated leaves are planned: a pack's `index.md` files are reserved
 * generated content the rebuild owns, so a leafless pack branch yields no
 * directory at all.
 */
function planGraft(args: {
  nodes: readonly NodeFile[];
  nodesDir: string;
  knowledgeDir: string;
  destinationDir: string;
  destinationName: string;
  manifestSummary: string;
  consumerLedger: RedirectsLedger;
  packLedger: RedirectsLedger;
}): GraftPlan {
  const leaves = args.nodes.map(node => ({
    src: node.path,
    dest: assertContained(
      args.nodesDir,
      join(args.destinationDir, ...node.relPath.split(posix.sep))
    ),
  }));
  const folderSummaries = mergeFolderSummaries(args);
  const redirectsMerged = Object.keys(args.packLedger).length;
  // Validation already refused every collision; this merge is conflict-free.
  const ledger =
    redirectsMerged > 0 ? mergeRedirectsLedgers(args.consumerLedger, args.packLedger).merged : null;
  const ids = new Set(args.nodes.map(node => node.frontmatter.kk_id));
  const grafted = args.nodes.map((node, i) => ({
    ...node,
    path: leaves[i]!.dest,
    relPath: posix.join(args.destinationName, node.relPath),
    relDir: posix.join(args.destinationName, node.relDir),
  }));
  return {
    destinationDir: args.destinationDir,
    leaves,
    grafted,
    ids,
    folderSummaries,
    ledger,
    redirectsMerged,
  };
}

/**
 * Runs every file the graft and its rebuild would write through the
 * containment boundary: the merged ledger, the consumer leaves the
 * rendered-link refresh will rewrite (planned over the grafted tree), the
 * rebuild's catalogs, indexes and sidecar, and `AGENTS.md` under the repo root
 * when its pointer block needs rewriting. A symlink at any of them would be
 * replaced by a regular file, so all refusals are aggregated and thrown.
 * Leaf destinations were checked when the plan was minted.
 */
function refuseUnsafeOutputs(
  root: string,
  plan: GraftPlan,
  consumerNodes: readonly NodeFile[],
  consumerLedger: RedirectsLedger
): void {
  const { kkDir, nodesDir } = repoPaths(root);
  const tree = [...consumerNodes, ...plan.grafted];
  const scope = new Set([...plan.ids, ...Object.keys(plan.ledger ?? {})]);
  const refreshed = planRenderedLinkRefresh(tree, plan.ledger ?? consumerLedger, scope);
  const nodeWrites = refreshed.map(({ node }) => node.path);
  if (plan.ledger !== null) nodeWrites.push(join(nodesDir, REDIRECTS_FILENAME));

  const failures: string[] = [];
  const check = (base: string, file: string, label: string): void => {
    try {
      assertContained(base, file, label);
    } catch (err) {
      failures.push(`  ${(err as Error).message}`);
    }
  };
  for (const file of nodeWrites) check(nodesDir, file, 'nodes/');
  for (const file of rebuildOutputFiles(root, tree)) check(kkDir, file, '.ai/kenkeep/');
  const agentsFile = join(root, 'AGENTS.md');
  if (agentsKkBlockNeedsWrite(agentsFile)) check(root, agentsFile, 'the repository root');
  if (failures.length > 0) {
    throw new Error(`refusing to replace a symlink:\n${[...new Set(failures)].join('\n')}`);
  }
}

/**
 * Write the plan. Leaves are copied byte-for-byte and the merged ledger is
 * written first, because the rendered-link refresh reads the ledger off disk.
 * The refresh covers the grafted leaves, consumer leaves linking to a grafted
 * id, and consumer leaves whose edge names a retired id. The sidecar merge
 * must land before the rebuild, which reads it off disk.
 */
function applyGraft(plan: GraftPlan, nodesDir: string): void {
  mkdirSync(plan.destinationDir, { recursive: true });
  for (const leaf of plan.leaves) atomicWriteFile(leaf.dest, readFileSync(leaf.src));
  if (plan.ledger !== null) writeRedirectsLedger(nodesDir, plan.ledger);
  refreshRenderedLinks(nodesDir, new Set([...plan.ids, ...Object.keys(plan.ledger ?? {})]));
  writeFolderSummaries(nodesDir, plan.folderSummaries);
}

/**
 * Refuses unless git can undo the import: the kenkeep root must sit in a git
 * work tree, and `.ai/kenkeep/` and the `AGENTS.md` the rebuild maintains must
 * have no uncommitted or untracked changes (git cannot restore an untracked
 * file) and no path flagged assume-unchanged or skip-worktree. Returns the commands that put both back to `HEAD`. Pathspecs are
 * relative to the git top level, so a kenkeep root nested in a monorepo works.
 */
function requireRestorableTree(root: string, kkDir: string): string[] {
  const git = (cwd: string, args: string[]): string =>
    execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  let top: string;
  try {
    top = git(root, ['rev-parse', '--show-toplevel']).trim();
  } catch {
    throw new Error(
      `${root} is not inside a git work tree. Import needs git to undo a failed graft; ` +
        'commit the knowledge base to a git repository first.'
    );
  }
  const quote = (arg: string): string =>
    /^[\w./@:+=-]+$/.test(arg) ? arg : `'${arg.replace(/'/g, `'\\''`)}'`;
  const realRoot = realpathSync(root);
  const toTop = (path: string): string => relative(top, path).split(sep).join(posix.sep);
  const kkSpec = toTop(join(realRoot, relative(root, kkDir)));
  const agentsSpec = toTop(join(realRoot, 'AGENTS.md'));

  const status = git(top, [
    'status',
    '--porcelain',
    '--untracked-files=all',
    '--',
    kkSpec,
    agentsSpec,
  ]);
  const dirty = status
    .split('\n')
    .filter(line => line !== '')
    .map(line => line.slice(3));
  if (dirty.length > 0) {
    throw new Error(
      `uncommitted changes in ${dirty.join(', ')}. Commit or stash them first, so a failed ` +
        'import can be undone with git.'
    );
  }
  // Status is not trusted alone: it hides edits to a path flagged
  // assume-unchanged or skip-worktree, `git restore` overwrites the first and
  // skips the second. `-v` tags a plain tracked entry `H`; lowercase is
  // assume-unchanged, `S`/`s` skip-worktree. Read-only: no flag is cleared.
  const flagged = git(top, ['ls-files', '-v', '-z', '--', kkSpec, agentsSpec])
    .split('\0')
    .filter(entry => entry !== '' && !entry.startsWith('H '))
    .map(entry => ({ tag: entry[0]!, path: entry.slice(2) }));
  if (flagged.length > 0) {
    // One command per flag: `git update-index` applies only the first of
    // `--no-assume-unchanged --no-skip-worktree` and ignores the second.
    const clear = flagged.flatMap(({ tag, path }) =>
      [
        ...(tag !== tag.toUpperCase() ? [`--no-assume-unchanged`] : []),
        ...(tag.toUpperCase() === 'S' ? [`--no-skip-worktree`] : []),
      ].map(option => `\`git -C ${quote(top)} update-index ${option} -- ${quote(path)}\``)
    );
    throw new Error(
      `${flagged.map(entry => entry.path).join(', ')} flagged assume-unchanged or ` +
        'skip-worktree, so git can neither report nor undo changes to them. Clear the ' +
        `flags with ${clear.join(', ')}, then commit first.`
    );
  }
  let agentsInHead: boolean;
  try {
    agentsInHead = git(top, ['ls-tree', '--name-only', 'HEAD', '--', agentsSpec]).trim() !== '';
  } catch {
    throw new Error('the repository has no commit yet. Commit the knowledge base first.');
  }

  const restorable = agentsInHead ? [kkSpec, agentsSpec] : [kkSpec];
  return [
    `git -C ${quote(top)} restore --source=HEAD --staged --worktree -- ${restorable.map(quote).join(' ')}`,
    `git -C ${quote(top)} clean -fd -- ${[kkSpec, agentsSpec].map(quote).join(' ')}`,
  ];
}

/**
 * Merge the pack's folder summary registry into the consumer's, re-keyed under
 * the destination branch, returning the map to write.
 *
 * `readFolderSummaries` returns an empty `Map` when the file is absent, so a
 * pack published before the registry existed merges to a no-op; that is the
 * backwards-compatibility path and needs no separate existence check.
 *
 * Ordering inside the merge is load-bearing: the consumer map seeds the result,
 * the destination subtree is cleared, the pack entries repopulate it, and
 * `manifest.summary` is applied last so it stays authoritative for the
 * destination key.
 *
 * Clearing the subtree first is what makes the pack the sole authority for the
 * branch it owns. Overwriting only the keys the pack supplies would strand any
 * key the pack no longer carries: nothing prunes the on-disk registry, since
 * `harvestFolderSummaries` prunes only its in-memory copy, so a `<dest>/gone`
 * key left by an earlier import of the same branch would survive indefinitely.
 * Keys outside the destination subtree belong to the consumer and are untouched.
 */
function mergeFolderSummaries(args: {
  knowledgeDir: string;
  nodesDir: string;
  destinationName: string;
  manifestSummary: string;
}): Map<string, string> {
  const merged = readFolderSummaries(args.nodesDir);
  const ownedPrefix = `${args.destinationName}/`;
  for (const key of [...merged.keys()]) {
    if (key === args.destinationName || key.startsWith(ownedPrefix)) merged.delete(key);
  }
  for (const [key, summary] of readFolderSummaries(args.knowledgeDir)) {
    merged.set(destinationKeyForPackKey(key, args.destinationName), summary);
  }
  merged.set(args.destinationName, args.manifestSummary);
  return merged;
}

/**
 * Re-key one pack registry entry as a prefix join under the destination branch:
 * the pack root maps to `<dest>` and `a/b` to `<dest>/a/b`.
 *
 * `validatePack` has already rejected keys that escape the knowledge tree, but
 * it neither normalizes them in place nor does `readFolderSummaries` normalize
 * on read, so a surviving key may still be `''`, `.`, `/` or `foo/`. Collapsing
 * those here rather than emitting `<dest>/.` and leaving `writeFolderSummaries`
 * to clean it up afterwards is what makes `manifest.summary` unconditionally
 * authoritative: two root-equivalent pack keys would otherwise reach the map as
 * distinct entries and their post-hoc collapse would resolve by insertion
 * order, letting a pack root entry beat the manifest.
 */
function destinationKeyForPackKey(key: string, destinationName: string): string {
  const normalized = posix.normalize(key.split(sep).join(posix.sep));
  if (normalized === '.' || normalized === '/') return destinationName;
  const trimmed = normalized.replace(/\/+$/u, '');
  return trimmed === '' ? destinationName : `${destinationName}/${trimmed}`;
}

function parseGitHubSource(source: string): GitHubRepo | null {
  const shorthand = /^([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)$/.exec(source);
  if (shorthand) return { owner: shorthand[1]!, repo: shorthand[2]!.replace(/\.git$/, '') };

  let url: URL;
  try {
    url = new URL(source);
  } catch {
    return null;
  }
  if (url.protocol !== 'https:') return null;
  if (url.hostname !== 'github.com' && url.hostname !== 'www.github.com') return null;
  const [owner, repo] = url.pathname.split('/').filter(Boolean);
  if (!owner || !repo) return null;
  return { owner, repo: repo.replace(/\.git$/, '') };
}

async function resolveGitHubTarballUrl(repo: GitHubRepo): Promise<string> {
  const latest = await fetchJson(
    `https://api.github.com/repos/${repo.owner}/${repo.repo}/releases/latest`
  );
  if (latest.status === 200) {
    const tarball = latest.json['tarball_url'];
    if (typeof tarball !== 'string' || tarball === '') {
      throw new Error(`latest release for ${repo.owner}/${repo.repo} has no tarball_url`);
    }
    return tarball;
  }
  if (latest.status !== 404) {
    throw new Error(`GitHub latest release lookup failed with HTTP ${latest.status}`);
  }

  const info = await fetchJson(`https://api.github.com/repos/${repo.owner}/${repo.repo}`);
  if (info.status !== 200) {
    throw new Error(`GitHub repository lookup failed with HTTP ${info.status}`);
  }
  const branch = info.json['default_branch'];
  if (typeof branch !== 'string' || branch === '') {
    throw new Error(`GitHub repository ${repo.owner}/${repo.repo} has no default_branch`);
  }
  return `https://api.github.com/repos/${repo.owner}/${repo.repo}/tarball/${encodeURIComponent(branch)}`;
}

async function fetchJson(url: string): Promise<{ status: number; json: Record<string, unknown> }> {
  const response = await fetch(url, { headers: { Accept: 'application/vnd.github+json' } });
  if (!response.ok) return { status: response.status, json: {} };
  const parsed = (await response.json()) as unknown;
  return {
    status: response.status,
    json:
      parsed && typeof parsed === 'object' && !Array.isArray(parsed)
        ? (parsed as Record<string, unknown>)
        : {},
  };
}

async function downloadTarball(url: string, file: string): Promise<string> {
  const response = await fetch(url, { headers: { Accept: 'application/vnd.github+json' } });
  if (!response.ok) {
    throw new Error(`tarball download failed with HTTP ${response.status}`);
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, Buffer.from(await response.arrayBuffer()));
  return file;
}

/**
 * Extraction goes to a private temp directory and preserves symlinks as
 * symlinks (no `-h`), so `findPackSymlinks` sees exactly what the archive
 * carried and refuses it before any read; nothing is followed during
 * extraction either (GNU tar defers symlink creation until the end).
 */
async function extractTarball(tarball: string, destination: string): Promise<void> {
  mkdirSync(destination, { recursive: true });
  await exec('tar', ['-xzf', tarball, '-C', destination]);
}

/** Whether a directory entry exists without following it (a dangling link counts). */
function entryExists(path: string): boolean {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Finds the one directory carrying the manifest. The presence test does not
 * follow links, so a symlinked manifest locates the root and is then refused
 * by the structural scan with its real cause, instead of being resolved here.
 */
function locatePackRoot(extractedDir: string): string {
  const matches: string[] = [];
  const walk = (dir: string): void => {
    if (entryExists(join(dir, PACK_MANIFEST_FILENAME))) {
      matches.push(dir);
      return;
    }
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) walk(join(dir, entry.name));
    }
  };
  walk(extractedDir);
  if (matches.length === 0) {
    throw new Error(
      `extracted pack does not contain ${PACK_MANIFEST_FILENAME} at the root or a wrapping directory`
    );
  }
  if (matches.length > 1) {
    const rel = matches.map(match => relative(extractedDir, match) || basename(match)).sort();
    throw new Error(`extracted pack contains multiple manifests: ${rel.join(', ')}`);
  }
  const [root] = matches;
  if (!root || !statSync(root).isDirectory()) {
    throw new Error(`located pack root is not a directory`);
  }
  return root;
}
